### PR TITLE
Added the author name of the meme along with the url

### PR DESCRIPTION
**Pull request by Rancho2002**
Modified the codebase with hashmap data structure so that in the future so that we can add more values related to the meme

Fixes the issue: #57

### CODE REVIEW

**Comment by Rancho2002** [comment]
Hi @rohan472000 please review and merge

**Comment by Rancho2002** [comment]
Hi @rohan472000 also add the hacktoberfest label pls

**Comment by Rancho2002** [comment]
Hi @rohan472000 every time conflict occurs pls fix it

**Comment by rohan472000** [comment]
kindly resolve above erorrs and provide screenshots of results for this PR.

**Comment by Rancho2002** [comment]
Please check now @rohan472000

**Comment by rohan472000** [comment]
Those small fixes will be done later.

**Comment by Rancho2002** [comment]
Please add the hacktoberfest labels?

**Comment by Rancho2002** [comment]
image
still showing zero, what to do @rohan472000

**Comment by rohan472000** [comment]
wait for 15min and then check.

**Comment by Rancho2002** [comment]
> wait for 15min and then check.

Thank you @rohan472000.

**Pull request merged**
