### PR TITLE
Create discord_bot.py

### PR DESCRIPTION
**Pull request by DevAgrawal04**
Fixes Issue #35

Created a discord bot which can be present in your server, and whenever you type in !postmeme it posts a meme on the channel.
Bot Invite Link: https://discord.com/api/oauth2/authorize?client_id=1158445141066002432&permissions=274877942784&scope=bot

image

### CODE REVIEW

**Comment by rohan472000** [comment]
@DevAgrawal04 gitguardian found the token which is a secret...for now you just remove it from here...due to security issue......but tomorrow morning when I ask here then send me as I will keep as git secret which will be safe.

**Comment by DevAgrawal04** [comment]
> @DevAgrawal04 gitguardian found the token which is a secret...for now you just remove it from here...due to security issue......but tomorrow morning when I ask here then send me as I will keep as git secret which will be safe.

Sure, but could you elaborate on how I should share the token?

**Comment by rohan472000** [comment]
On my LinkedIn inbox, you can find it on my GitHub profile.

**Review by DevAgrawal04 — COMMENTED** [review]
Removed the token

**Comment by rohan472000** [comment]
Better delete old token and regenerate again.

**Comment by DevAgrawal04** [comment]
> Better delete old token and regenerate again.

I have the new token, however I cannot mention it on GitHub

**Comment by rohan472000** [comment]
I m not able to get into that discord channel as it is asking for a server.

**Comment by DevAgrawal04** [comment]
> In previous push, you have disclosed secret token so gitguardian will not pass , no worries for that.
> 
> 
> I m not able to get into that discord channel as it is asking for a server.

In the first commented line, I've provided the invite link. Paste the invite link in a browser, and you should be able to invite the bot to a server. You might need tobe a moderator or owner of a server to have the required permissions to add bots to servers.

Once the bot has arrived in your server, you will see the bot name in participants. Run the script, and the bot will come online to the server. 
Type in !postmeme in a channel which is open to the bot, and you should have a new meme to look at.

**Comment by rohan472000** [comment]
Screenshot_20231003-112649

**Comment by DevAgrawal04** [comment]
> Screenshot_20231003-112649
> 

This implies that you currently do not have permissions to add bots in servers you're part of. You could make a new server, and since you'd be the owner of that server; you'll have all the required permissions to add a bot in your personal server.

**Comment by rohan472000** [comment]
Screenshot_20231003-121401

**Pull request merged**
