### PR TITLE
added a cli tool that allow user to fetch the meme thats the current meme on the readme

### PR DESCRIPTION
**Pull request by hrdkmishra**

### CODE REVIEW

**Comment by rohan472000** [comment]
What's its use???

**Comment by hrdkmishra** [comment]
one can view the meme from the terminal

**Comment by rohan472000** [comment]
Well idea to include CLI is nice but just for fetching current meme is bit limited, as we r trying to post meme on twitter, on discord, making it executable, first let these issue to be completed then CLI will be implemented....till then try to contribute on above mentioned issues.

**Comment by hrdkmishra** [comment]
well i can also try to make use of joke.py and make a script the fetch meme directly using joke.py instead of readme

**Comment by rohan472000** [comment]
Do as you wish but it should have some impact :)

**Comment by hrdkmishra** [comment]
so the cli isnt impactful ? since we already have discord and twitter what else is left?

**Comment by rohan472000** [comment]
Discord is still not working with GitHub actions for now, Twitter worked but api is paid, but CLI has to do lot of thinks not just fetching memes.

I want to add all these things into one .exe file which when installed then can do all stuffs with UI and with cli also.

**Comment by rohan472000** [comment]
@hrdkmishra first resolve the conflicts.

**Pull request closed without merging**
