### PR TITLE
Feature/Build Check for PRs

### LINKED ISSUE #10: Help needed implementing new build check to test PRs
Issue Description:

I want to add a new build check to test PRs before merging. This will help to ensure that new codes do not break the existing functionality of the repository.

If you are interested to implement the build check, please raise a PR. 

Additional Information:

- The repository is written in Python.
- The build check should be run on every PR.
- The build check should fail if any wrong or incompatible code are added to 
   the README.md file and they break the existing functionality of the repository.

### PR DESCRIPTION
**Pull request by Prikshit7766**
**Description:**

This PR implements a new build check for pull requests (PRs) to ensure that new code changes do not break the existing functionality of the repository. Here are the details:

- Fix #10

**Changes Made:**

- Added a new GitHub Actions workflow file named `build-check.yml`.
- Configured the workflow to run on every PR targeting the `main` branch.
- The workflow checks the Python code, ensures dependencies are correctly installed, and verifies that the README.md file does not contain wrong or incompatible code.

**Testing:**

- The workflow includes linting with Flake8 and running unit tests to verify the functionality.
- It has been tested on multiple Python versions (3.7, 3.8, and 3.9) and both Ubuntu and Windows environments.

**Other Changes:**

- Updated the .gitignore file to ignore
- Resolved Flake8 linting issues in the `joke.py` file.
- Ensured that the `requirements.txt` file is up to date.
- Added a new unit test file test_readme.py to validate specific sections in the README.md file.

### CODE REVIEW

**Comment by rohan472000** [comment]
@joelmathewphilip can you look into it once?

**Comment by rohan472000** [comment]
@Prikshit7766 , Need this check so that we can see how any PR will look like after merge, will it affect meme fetching or any other commit issue, I hope you have understood the requirement.

**Comment by joelmathewphilip** [comment]
The pipeline looks good. The test cases can be more elaborate.

**Comment by Prikshit7766** [comment]
We wcan create a dedicated test for `joke.py` to verify the 'meme fetching'  functionality works correctly both before and after the PR is applied.

**Comment by Prikshit7766** [comment]
@rohan472000 I've made some changes to the code. Could you please review it and let me know if everything looks fine.

**Review by rohan472000 — APPROVED** [review]

**Pull request merged**
