### PR TITLE
updated readme_disclaimer

### PR DESCRIPTION
**Pull request by flashpunch0-0**
# Disclaimer

The memes displayed in this project's README are sourced from Reddit. We want to emphasize that we do not claim ownership of these memes, and they are the creative work of Reddit users. Our intent is to showcase these memes purely for non-commercial purposes.

## Creator's Recognition

We deeply appreciate the creativity and efforts put forth by Reddit users in creating these memes. The humor and wit are a testament to the wonderful community on Reddit.

## Request for Modification

If you are the creator of one of these memes and have any concerns regarding its usage, attribution, or wish for its removal, please feel free to contact us. We highly value your creative work and are committed to addressing your requests promptly.

**Your artistic contributions deserve proper recognition and respect. Thank you for being part of the vibrant Reddit community!**

### CODE REVIEW

**Comment by rohan472000** [comment]
Kindly fix above errors.

**Comment by flashpunch0-0** [comment]
kindly check if errors are fixed

**Comment by rohan472000** [comment]
Nope...few static errors are there.

**Comment by rohan472000** [comment]
Btw you can also check in failed build in down workflows.

**Pull request closed without merging**
