### PR TITLE
Replaced markdown with inline HTML and implemented beautifulsoup for parsing ReadMe

### PR DESCRIPTION
**Pull request by prateiku**
- Updated the markdown which holds the image URLto an inline html `img` tag.
- Implemented beautifulsoup to parse readme to effectively update the url.
- Added author credits to the meme.

### CODE REVIEW

**Comment by rohan472000** [comment]
add screenshots of your results/output.

**Comment by prateiku** [comment]
image
Checkout the inline css customization offered by img tag. You can set custom image size, border, border-color.

Screenshot (14)
Displays the name of the author on mouse-hover.

Apart from these visual changes the way the readme file is parsed and modified is also improved.

**Comment by rohan472000** [comment]
can you make it square, give ss of results.

**Comment by prateiku** [comment]
image

**Review by rohan472000 — APPROVED** [review]

**Comment by prateiku** [comment]
Done.

**Comment by rohan472000** [comment]
Can you do `ruff . --fix` in joke.py in your IDE to get rid off build errors.

**Comment by prateiku** [comment]
I am resolving the conflict still the conflict arises due to continuous commits to the readme file by github actions.
I think you'll have to stop the job that commits readme -> resolve this conflict -> merge -> start the job again.

**Comment by rohan472000** [comment]
@prateiku apologies for the late reply, I was busy at office meetings and travel, i will look into it tomorrow.

**Pull request closed without merging**
